title: Rajat Chahar
email: rajatkumarchahar@gmail.com
description: "Hey ğŸ‘‹ğŸ¼, Iâ€™m Rajat â€” I build tech, lead teams, and share thoughts on things I learn along the way. This blog is a mix of ideas, experiments, and lessons from building at scale. â¤ï¸"
baseurl: ""
url: "https://froxtrost.github.io"
twitter: https://twitter.com/yourusername
github: https://github.com/froxtrost
profile_image: /assets/images/rajat.jpeg

permalink: /:slug.html

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)

theme: no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: "â†" # customize text for homepage link in post layout
  date_format: "%d-%m-%Y" # customize how date is formatted
  show_description: false # show blog description in home page

sass:
  style: compressed

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

plugins:
  - jekyll-feed
  - jekyll-seo-tag

safe: false
